services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/usr/src/app/output
      - ./env/diff.yml:/usr/src/app/env/diff.yml:ro
      - ./env/screenshot.yml:/usr/src/app/env/screenshot.yml:ro
    environment:
      - NODE_ENV=production
    init: true