services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/usr/src/app/output
      - ./env:/usr/src/app/env:ro
    environment:
      - NODE_ENV=production
    init: true