output_directory: "screenshots"
screenshots:
  - url: "https://example.com"
    filename: "example"
  - url: "https://github.com"
    filename: "github"
  - url: "https://google.com"
    filename: "google"
