name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
    steps:
      - uses: actions/checkout@v3

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            build-essential \
            libcairo2-dev \
            libjpeg-dev \
            libpango1.0-dev \
            libgif-dev

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
